
[build]
  # Your build command
  command = "npm run build" # or "yarn build"
  # The directory to publish (your build output)
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200